# This is a basic workflow that is manually triggered
name: Build several build configs
on: 
  pull_request:
    branches:    
      - sep_socwatch_linux_*
jobs:
  build:
    name: BUILD_KERNEL_TREE
    runs-on: kernel-build
    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.sha }}
    - name : Clean 
      run : make distclean  && make clean
    - name : Build defconfig
      run : make defconfig && make -j `nproc`
    - name : Build allyesconfig x86_64
      run : make allyesconfig ARCH=x86_64 && make -j `nproc`
    - name : Build allmodconfig x86_64
      run : make allmodconfig ARCH=x86_64 && make -j `nproc`
    - name : Build allnoconfig x86_64
      run : make allnoconfig ARCH=x86_64 && make -j `nproc`

